#!/usr/bin/env bash
# script that installs nginx on the web-01 server

sudo apt-get update -y
sudo apt-get upgrade -y

sudo apt-get install nginx -y
sudo service nginx start

echo "Hello World!" > /var/www/html/index.nginx-debian.html
