#!/usr/bin/env bash
# script that installs nginx on the web-01 server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
# Check if nginx services are active
sudo service nginx start

sudo -i "/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
# Restart nginx to save the changes
sudo service nginx restart
