#!/usr/bin/env bash
# script that configures server web-02 as web-01

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html

sudo sed -i "/server_name _;/ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# customize 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/server_name _;/ a error_page 404/404.html;" /etc/nginx/sites-available/default

#Configure customize response header
sudo sed -i "/server_name _;/ a add_header X-Served-By $(hostname)" /etc/nginx/sites-available/default 

# Restart nginx to save the changes
sudo service nginx restart
