#!/usr/bin/env bash
#this script kills 7-highlander process
touch /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid
while true
do
	trap 'echo "I hate the kill command" | rm "/var/run/myscript.pid" | kill -9 "$$"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm "/var/run/myscript.pid" | kill -9 "$$"' SIGQUIT
	echo "To infinity and beyond"
done
