#!/usr/bin/env bash
#this script displays To infinity and beyond indefinitely, and I'm invincible!!! when receiving a SIGTERM signal
while true
do
	if [[ $SIGTERM ]]
	then
		echo "I'm invincible!!!"
	fi
	echo "To infinity and beyond"
	sleep 2
	
done
