#!/usr/bin/env bash  
#For Loop to Read Three-expression
number=1
while [[ number -le 100 ]]
do
	if (( number % 3 == 0 && number % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( number % 5 == 0 ))
	then
		echo "Buzz"
	elif (( number % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$number"
	fi
	((number++))
done

