#!/usr/bin/env bash  
#script that checks if a file exists, is a regular file and if is empty
File=school
if [[ -e "$File" ]]
then
	echo "$File file exists"
	if [[ -s "$File" ]]
	then
		echo "$File file is not empty"
	else
		echo "$File file is empty"
	fi
	if [[ -f "$File" ]]
	then
		echo "$File is a regular file"
	fi
else
	echo "$File file does not exists"
fi

